添加 atsrv_socket 软件包代码
RT-Thread-packages/atsrv_socket pull request #1
Opened 2019-04-26 03:22 UTC by shaoguoji

[
1. 添加 AT 指令实现
2. 编写 README.md
3. STM32 Keil 编译运行测试通过
]

2019-04-26 04:00 UTC, aozima approved these changes

2019-04-26 04:03 UTC, aozima requested changes

2019-04-26 04:03 UTC, aozima commented on src/ip/at_ipsend.c
> +    sendbuffer = (uint8_t *)malloc(2048);
1. 此次不要使用固定数值
2. malloc应该要判断结果

2019-04-26 04:05 UTC, armink reviewed
@Lawlieta review 一下吧

2019-04-26 04:05 UTC, armink commented on README.md
> +|--------------|----------------------|
基础的 AT 命令可以放在 AT Server 组件中吗？我记得 ATE/ATZ 这些好像在那边都有实现

2019-04-26 04:09 UTC, shaoguoji commented on README.md
> +|--------------|----------------------|
是的，基础的在那边已经实现，文档和 menuconfig 菜单中只是列举展示。

2019-04-26 10:48 UTC, Lawlieta commented on README.md
> +- RT-Thread 3.0+
3.1.0+

2019-04-26 10:48 UTC, Lawlieta commented on README.md
> +| AT+CIPSEND   | 发送数据             |
针对 WIFI 模块，设置 DNS 服务器地址，设置 DHCP 状态，设置 IP 地址等命令后面是否可以支持一下，netdev 组件中可能有使用到。

2019-04-26 10:48 UTC, Lawlieta commented on README.md
> +* 更多文档位于 [`/docs`](/docs) 下，使用前 **务必查看**
好像没有doc目录

2019-04-26 10:48 UTC, Lawlieta commented on src/ip/at_ipmode.c
> +
未实现 TODO？？

2019-04-26 10:48 UTC, Lawlieta commented on src/ip/at_ipping.c
> +//        if(at_ping(domain, 0) != RT_EOK)
这里 ping 的实现可以考虑上 netdev 组件，通过获取网卡设备对象，使用其中的 ping ops 操作函数，返回对应的 ttl，timeout，data_len，ip等信息

2019-04-26 10:48 UTC, Lawlieta commented on src/ip/at_ipsend.c
> +    sendbuffer = (uint8_t *)malloc(2048);
建议使用rt_malloc 和 rt_free

2019-04-26 10:48 UTC, Lawlieta commented on src/ip/at_ipstart.c
> +#define DBG_SECTION_NAME  "[AT/IP]"
最新 rtdbg 宏定义有改动

#define DBG_TAG       "atsrv.ip"
#define DBG_LVL         DBG_LOG

其他宏不需要定义

2019-04-26 10:48 UTC, Lawlieta commented on src/ip/at_ipstart.c
> +                if((result = at_req_parse_args(args, "=%*[\"]%[^\"]%*[\"],%*[\"]%[^\"]%*[\"],%d,%d", connection_type, remote_addr, &port, &alive)) <= 0)
类似的解析函数前多添加注释吧，说明解析的不同命令的格式

2019-04-26 10:48 UTC, Lawlieta commented on src/ip/at_ipstatus.c
> +    int status = 5;
5，2，4  分别什么意思，建议定义宏，添加注释

2019-04-26 10:48 UTC, Lawlieta commented on src/wifi/at_connect.c
> +#define AT_VERSION "0.0.1"
这个 AT_VERSION 好像没用到

2019-04-26 10:48 UTC, Lawlieta commented on src/wifi/at_disconnect.c
> +    return AT_RESULT_OK;
最好需要考虑一些 WIFI 主动断开和连接的情况。

这类 AT 服务器主动下发数据的情况需要 URC 处理机制，可以在软件包中考虑一下 URC 的发送方式，简单点的创建线程等待事件，获取事件主动发送数据到 AT 客户端

2019-04-26 10:48 UTC, Lawlieta commented on src/ip/at_ipstop.c
> +extern int single_connect_fd;
整体看来，很多文件中使用了去全局变量来判断一些状态或者存放 socket值，建议可以定义结构体统一存储必要的信息，方便信息的获取和使用。类似下面定义：

```c
#define AT_SVR_SOCKET_NUM  4

struct struct at_svr_socket
{
    int scoket;
    int port;
    enum at_srv_socket_type type;
    void *user_data;
}

typedef struct at_svr_info
{
    struct at_server *server;
    struct at_svr_socket sockets[AT_SVR_SOCKET_NUM];
    
    int ip_mode;
    int signal_connect_fd;
    
    int wifi_mode;          /* SoftAP, Station */
    int wifi_is_connect;    /* WIFI 是否连接 */
    
    struct netdev *netdev;  /* 如果要添加设置 IP 地址等命令可以使用 netdev 组件 */
    
    void *user_data;
}

```
定义一个全局的结构体用于存储信息即可

2019-04-27 12:07 UTC, shaoguoji commented on README.md
> +* 更多文档位于 [`/docs`](/docs) 下，使用前 **务必查看**
已更正

2019-04-27 12:07 UTC, shaoguoji commented on README.md
> +- RT-Thread 3.0+
已更正

2019-04-28 02:43 UTC, shaoguoji commented on src/ip/at_ipmode.c
> +
这里意思只需把参数 parse 到变量 ipmode 即可，已改为判断失败情况。

2019-04-28 02:43 UTC, shaoguoji commented on src/ip/at_ipstatus.c
> +    int status = 5;
已添加宏定义和注释

2019-04-28 02:43 UTC, shaoguoji commented on src/wifi/at_connect.c
> +#define AT_VERSION "0.0.1"
已移除

2019-04-29 09:25 UTC, merged